### ISSUE TITLE
Bounty Bank [Bug + Flaw]

### ISSUE THREAD

**Issue by CzEMC** [Asiru/HeadHunter#1]
Players are able to add bounty to players that never joined the server, or inactive players. They do this to bypass the 10% subtraction from their balance when they die. They take the money off the bounty to get it back. This causes server errors when the server restarts. It also breaks the bounty system some times.

Want the logs? Ask in a reply.

**Comment by Asiru** [comment]
I can add it to the next update.  You could've just messaged me on Spigot
by the way.
