### ISSUE TITLE
No Head Drop on Flame Death [No Listener Implemented?]

### ISSUE THREAD

**Issue by CzEMC** [Asiru/HeadHunter#2]
Any time a player is killed via firetick from Fire Aspect on a sword or from flame on a bow, their head does not drop. is this a Bug or is the listener not implemented?

Sorry that I don't use Spigotmc for bug reporting, I'm used to using Github.

**Comment by Asiru** [comment]
Oh okay, that's alright.

Well, that feature isn't implemented.  I haven't looked into it yet, but
I'm sorry to say I'm not sure if it's possible.  Right now it's only set to
drop when a player delivers the killing blow.

**Comment by CzEMC** [comment]
Can there be a config option that we can set so a head drops on any death? Many players are complaining about not getting heads due to this.

**Comment by Asiru** [comment]
Ehhhhhhh...  Any death?  Really?

**Comment by CzEMC** [comment]
Just until the feature is added. Add here: PlayerListeners.java

After line 40, add a else if?

**Comment by Asiru** [comment]
Yes that's where it would go, but I'm not sure if I can check the, like
"fire cause".

**Comment by CzEMC** [comment]
firetick you mean?

**Comment by Asiru** [comment]
Well, fireticks are involved, yes.  But I mean the reason the player HAS
fireticks.

**Comment by CzEMC** [comment]
Im looking at Bukkit api right now for it

**Comment by Asiru** [comment]
As am I :P

**Comment by Asiru** [comment]
Are you familiar with the EntityDamageEvent.DamageCause enumerator?

If so, do you know if a fire aspect or flame weapon causes DamageCause.FIRE
or just DamageCause.FIRE_TICK?

**Comment by CzEMC** [comment]
Is it possible to check getDeathMessage that is returned from PlayerDeathEvent and test if it contains "burnt to crisp" or what ever minecraft returns when a player dies from fire tick?

**Comment by Asiru** [comment]
Well I can't do that because some plugins change the death message :/

**Comment by CzEMC** [comment]
Located here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html

It returns FIRE_TICK

**Comment by CzEMC** [comment]
If the player dies from being on fire. it will return FIRE_TICK

**Comment by Asiru** [comment]
Yes I've seen that, but I wasn't sure if a fire aspect sword also caused
the FIRE DamageCause as well.  I guess it doesn't really matter.  It would
probably be either ENTITY_ATTACK or FIRE_TICK.

**Comment by CzEMC** [comment]
As long as the player dies from being on fire, It should return FIRE_TICK...

**Comment by Asiru** [comment]
Right.  The hard part is figuring out whether they were lit on fire by a
player's weapon or something else.

**Comment by CzEMC** [comment]
Can you still add the config option?

**Comment by Asiru** [comment]
I can.
